<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.apigateway</groupId>
  <artifactId>api-gateway</artifactId>
  <version>1.0.0</version>
  <name>api-gateway</name>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <exec.mainClass>com.apigateway.core.GatewayServer</exec.mainClass>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <mainClass>${exec.mainClass}</mainClass>
        </configuration>
        <executions>
          <execution>
            <id>gateway</id>
            <configuration>
              <mainClass>com.apigateway.core.GatewayServer</mainClass>
            </configuration>
          </execution>
          <execution>
            <id>backend-sim</id>
            <configuration>
              <mainClass>com.apigateway.simulator.BackendSimulatorServer</mainClass>
            </configuration>
          </execution>
          <execution>
            <id>load-sim</id>
            <configuration>
              <mainClass>com.apigateway.simulator.LoadSimulatorServer</mainClass>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
